name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Deps
      run: |
        emd=$(which eatmydata) || :
        sudo $emd ./setup install-packages

    - name: Install Golang
      run: |
        . ./.github/workflows/env
        ./setup install-go
        which go
        go env
        go version

    - name: Build squashfs-tools-ng
      run: |
        . ./.github/workflows/env
        ./setup $MYLOCAL

    - name: Build
      run: |
        . ./.github/workflows/env
        which go
        go version
        make all
        make static

    - name: Test
      run: |
        . ./.github/workflows/env
        make test

    - name: Copy binaries
      run: |
        . ./.github/workflows/env
        mkdir -p bin
        cp squashtool/squashtool bin/squashtool.dynamic
        cp squashtool/squashtool.static bin/squashtool

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/
        if-no-files-found: error

    - name: Release bin
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/squashtool
          bin/squashtool.dynamic
