name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: |
        . ./.github/workflows/env
        ./setup --install-packages $MYLOCAL

    - name: Build
      run: |
        . ./.github/workflows/env
        make all
        make static

    - name: Test
      run: |
        . ./.github/workflows/env
        make test
